    steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/arbitrageboosterbot:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/arbitrageboosterbot:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'arbitrageboosterbot'
    - '--image'
    - 'gcr.io/$PROJECT_ID/arbitrageboosterbot:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
  images:
  - 'gcr.io/$PROJECT_ID/arbitrageboosterbot:$COMMIT_SHA'
  steps:
  - name: 'gcr.io/cloudbuild/docker'
    args: ['build', '-t', 'my-image', '.']
  # 指定 logs_bucket
  logs_bucket: 'continual-modem-381615.appspot.com'
  # 使用 REGIONAL_USER_OWNED_BUCKET 選項
  options:
    default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'
  # 使用 CLOUD_LOGGING_ONLY 選項
  options:
    logging: 'CLOUD_LOGGING_ONLY'
